version: '2'

services:
  apache:
    container_name: docker-apache
    image: docker-apache:latest
    restart: on-failure
    hostname: docker-apache
    ports:
      - "80:80"
    command: bash /tmp/scripts/execute-scripts.sh

  mysql:
    container_name: docker-mysql
    image: docker-mysql:latest
    restart: on-failure
    hostname: docker-mysql
    command: bash /tmp/scripts/execute-scripts.sh
